// Hand-rolled migrator: applies every SQL file listed in
// migrations/meta/_journal.json that hasn't been recorded in the
// _bg_migrations tracking table.
//
// Why not `drizzle-kit migrate`? Our migrations include data-preserving
// transformations (enum reshapes with USING clauses, backfills) that we
// hand-write. drizzle-kit migrate would still run them, but it owns its
// own `__drizzle_migrations` table and assumes the SQL was generated by
// drizzle-kit. We keep them separate to make it obvious that the SQL is
// authoritative and the schema files just describe the target shape.
//
// Each migration runs in a transaction. We split on
// `--> statement-breakpoint` (drizzle's own marker) so multi-statement
// files can apply individual DDL statements without bumping into pg's
// "cannot run inside a transaction block" limits for some types — those
// would need to move out of the breakpoint block explicitly.

import { readFileSync } from "node:fs";
import { join } from "node:path";
import pg from "pg";

interface JournalEntry {
  idx: number;
  version: string;
  when: number;
  tag: string;
  breakpoints: boolean;
}

interface Journal {
  version: string;
  dialect: string;
  entries: JournalEntry[];
}

const MIGRATIONS_DIR = join(import.meta.dirname, "..", "migrations");
const JOURNAL_PATH = join(MIGRATIONS_DIR, "meta", "_journal.json");
const TRACKING_TABLE = "_bg_migrations";

function parseArgs(argv: string[]): { markUpTo: string | null; status: boolean } {
  let markUpTo: string | null = null;
  let status = false;
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--mark-up-to") {
      const v = argv[i + 1];
      if (!v) throw new Error("--mark-up-to needs a tag");
      markUpTo = v;
      i++;
    } else if (a === "--status") {
      status = true;
    } else if (a === "--help" || a === "-h") {
      console.log(
        "Usage:\n" +
          "  pnpm db:migrate                       apply pending migrations\n" +
          "  pnpm db:migrate --status              show which tags are applied\n" +
          "  pnpm db:migrate --mark-up-to <tag>    mark every migration up to <tag>\n" +
          "                                        as applied without running it",
      );
      process.exit(0);
    }
  }
  return { markUpTo, status };
}

async function main(): Promise<void> {
  const { markUpTo, status } = parseArgs(process.argv.slice(2));
  const url =
    process.env.DATABASE_URL ?? "postgres://bgreen:bgreen_dev@localhost:5432/bgreen";
  const journal = JSON.parse(readFileSync(JOURNAL_PATH, "utf8")) as Journal;
  const entries = [...journal.entries].sort((a, b) => a.idx - b.idx);

  const pool = new pg.Pool({ connectionString: url });
  try {
    await ensureTrackingTable(pool);

    if (status) {
      const applied = await listApplied(pool);
      for (const entry of entries) {
        const flag = applied.has(entry.tag) ? "✓" : " ";
        console.log(`[${flag}] ${entry.tag}`);
      }
      return;
    }

    if (markUpTo) {
      const matched = entries.find((e) => e.tag === markUpTo);
      if (!matched) {
        throw new Error(`--mark-up-to: unknown tag '${markUpTo}'`);
      }
      const applied = await listApplied(pool);
      let count = 0;
      for (const entry of entries) {
        if (entry.idx > matched.idx) break;
        if (applied.has(entry.tag)) continue;
        await pool.query(
          `INSERT INTO "${TRACKING_TABLE}" (tag, idx) VALUES ($1, $2)
           ON CONFLICT (tag) DO NOTHING`,
          [entry.tag, entry.idx],
        );
        console.log(`marked   ${entry.tag} (not executed)`);
        count += 1;
      }
      console.log(`done — marked ${count} migration(s) as applied`);
      return;
    }

    const applied = await listApplied(pool);
    let count = 0;
    for (const entry of entries) {
      if (applied.has(entry.tag)) {
        console.log(`skipped  ${entry.tag} (already applied)`);
        continue;
      }
      const sqlPath = join(MIGRATIONS_DIR, `${entry.tag}.sql`);
      const sql = readFileSync(sqlPath, "utf8");
      await applyMigration(pool, entry, sql);
      console.log(`applied  ${entry.tag}`);
      count += 1;
    }
    if (count === 0) console.log("all migrations already applied");
    else console.log(`done — applied ${count} migration(s)`);
  } finally {
    await pool.end();
  }
}

async function ensureTrackingTable(pool: pg.Pool): Promise<void> {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS "${TRACKING_TABLE}" (
      "tag" text PRIMARY KEY,
      "idx" integer NOT NULL,
      "applied_at" timestamp with time zone NOT NULL DEFAULT now()
    )
  `);
}

async function listApplied(pool: pg.Pool): Promise<Set<string>> {
  const res = await pool.query<{ tag: string }>(`SELECT tag FROM "${TRACKING_TABLE}"`);
  return new Set(res.rows.map((r) => r.tag));
}

async function applyMigration(
  pool: pg.Pool,
  entry: JournalEntry,
  sql: string,
): Promise<void> {
  // Split on drizzle's statement-breakpoint marker. Empty / whitespace-only
  // chunks are dropped so a trailing breakpoint doesn't trigger an empty
  // query.
  const statements = sql
    .split("--> statement-breakpoint")
    .map((s) => s.trim())
    .filter((s) => s.length > 0);

  const client = await pool.connect();
  try {
    await client.query("BEGIN");
    for (const stmt of statements) {
      await client.query(stmt);
    }
    await client.query(`INSERT INTO "${TRACKING_TABLE}" (tag, idx) VALUES ($1, $2)`, [
      entry.tag,
      entry.idx,
    ]);
    await client.query("COMMIT");
  } catch (err) {
    await client.query("ROLLBACK").catch(() => {});
    throw new Error(`failed applying ${entry.tag}: ${(err as Error).message}`, { cause: err });
  } finally {
    client.release();
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
